#!/usr/bin/env bash
# Regenerate the Cloudflare IP allowlist for nginx from cloudflare.com/ips:
#   /etc/nginx/cloudflare-allow.conf — allow lines (the site denies all else)
#
# The allowlist is enforced in nginx, NOT the host firewall: fr-0 is the NAT
# gateway for the BP subnet (masquerade), and enabling ufw there would default-
# drop forwarding — a blast radius far bigger than the dashboard. nginx-level
# deny gives the same effect (non-Cloudflare clients get 403) with zero risk to
# the relay/BP path.
#
# Re-run whenever Cloudflare updates its ranges (rare; they announce it).
set -euo pipefail

V4=$(curl -fsS https://www.cloudflare.com/ips-v4)
V6=$(curl -fsS https://www.cloudflare.com/ips-v6)
[ -n "$V4" ] || { echo "failed to fetch CF ipv4 ranges" >&2; exit 1; }

tmp=$(mktemp)
{
  echo "# generated by deploy/cf-ips.sh on $(date -u +%F) — do not edit"
  for ip in $V4 $V6; do echo "allow $ip;"; done
} > "$tmp"
sudo mv "$tmp" /etc/nginx/cloudflare-allow.conf
sudo chmod 644 /etc/nginx/cloudflare-allow.conf
echo "wrote cloudflare-allow.conf ($(echo "$V4 $V6" | wc -w) ranges)"

sudo nginx -t && sudo systemctl reload nginx
